version: '3'
services:
  server:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    environment:
      - HOST=:9090
  client:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    environment:
      - HOST=server:9090